### ISSUE TITLE
Completion tests cannot run against the stable wave, which blocks a stable release

### ISSUE THREAD

**Issue by olsh** [olsh/resharper-structured-logging#201]
The completion tests added in #198 cannot run against the stable wave, so no stable release can be cut from `master` until this is fixed. Found by a dry run of the release dispatch: [run 35567978743](https://github.com/olsh/resharper-structured-logging/actions/runs/35567978743), `-f publish=false -f sdk-version=2026.2.2`.

`master` tracks the EAP train and a stable release is built from the same source with the `sdk-version` override, so every test has to pass on both waves. Two things stop that.

## 1. The test project does not compile on 2026.2

```
test/src/Completion/TemplatePropertyCamelCaseCompletionTests.cs(18,33): error CS0115:
'TemplatePropertyCamelCaseCompletionTests.SetupSettingsBeforeTest(ITextControl, IContextBoundSettingsStore)':
no suitable method found to override
```

`CodeCompletionTestBase.SetupSettingsBeforeTest` is new in 2026.3. In 2026.2 the type has no such member — confirmed by reading both `JetBrains.ReSharper.FeaturesTestFramework` assemblies:

| member | 262 | 263 |
| --- | :---: | :---: |
| `SetupSettingsBeforeTest` | — | yes |
| `DoTestSolution` / `DoTest` / `LookupItemFilter` / `Sorting` / `TestType` | yes | yes |

The plugin itself compiles fine on 2026.2; only the test project breaks.

**Fix, already written and verified:** use the hook the analyzer fixtures use, on the method they hang it on.

```csharp
protected override void DoTestSolution([NotNull] params string[] fileSet)
{
    ExecuteWithinSettingsTransaction(settingsStore =>
    {
        RunGuarded(() => MutateSettings(settingsStore));
        base.DoTestSolution(fileSet);
    });
}

protected virtual void MutateSettings([NotNull] IContextBoundSettingsStore settingsStore)
{
}
```

Note it has to be `DoTestSolution`, not `DoTest`: everything below `DoTestSolution` already runs inside the reentrancy guard, and wrapping `DoTest` fails with *"Reentrancy Guard is not clean"*.

With this alone, `build.cmd Test` is 273/273 on 2026.3.

## 2. The list golds record a rendering that changes between waves

With the compile fixed, 17 of the 33 completion tests fail on 2026.2 — exactly the list fixtures that produce items. The 6 action fixtures and the 10 fixtures that assert an empty list pass on both waves.

Every difference across all 17, in full:

```
17 ×   < Rules: [\w] => add_to_prefix
15 ×   < [FromLightEvaluation, NotObsolete, ObsoleteRuleApplied, NormalSelectionPriority, Other]
15 ×   > [FromSingleCompletion, FromLightAndDynamicEvaluation, NotObsolete, ObsoleteRuleApplied, NormalSelectionPriority, Other]
 2 ×   < [FromLightEvaluation, PrefixMatch, …]
 2 ×   > [FromSingleCompletion, FromLightAndDynamicEvaluation, PrefixMatch, …]
```

The item names, their order, `OrderStr`, the placement groups, the counts and the ranges are identical on both waves. 2026.3 added the `Rules:` header line and renamed the relevance categories; the gold records both because `CheckResultModernList` writes them and is not virtual.

So the feature behaves the same on the stable wave. It is the expectation format that is wave-specific.

## Ruled out

- **`RelevanceTypesForPresentation => Array.Empty<Type>()`** — the line does not disappear, it degrades to raw indices, `[62, 58, 21, 20, 7, 0]`, which are no more portable.
- **Keying `AdditionalGoldFileSuffix` on the loaded assembly** — the property is settable and the suffix mechanism works (it looked for `TestSerilogFirstHole.cs777.gold`), but JetBrains stamps every assembly `777.0.0.0`, file version included, so the wave cannot be read at run time.

## Proposed fix

Carry the SDK version into the test assembly at build time and key the gold on its wave:

```xml
<ItemGroup>
  <AssemblyMetadata Include="SdkVersion" Value="$(SdkVersion)" />
</ItemGroup>
```

```csharp
protected TemplatePropertyCompletionTestBase()
{
    // The gold records how the test framework renders a lookup list, and that rendering changes
    // between waves. The extension is released for the stable wave from this same source, so each
    // wave keeps its own expectation.
    AdditionalGoldFileSuffix = SdkWave;
}
```

Then generate both sets: 33 golds per wave, `build.cmd Test` for the EAP set and `build.cmd Test --sdk-version-override <stable>` for the other. Only the wave being adopted needs regenerating on a bump, so it stays at two sets rather than growing.

The cheaper alternative, if the doubled corpus is not wanted: have the 17 list fixtures stand down when built against a wave other than the one their golds came from. That ships the feature to stable covered by the action fixtures and the analyzer suite, but not by the name-selection golds.

## Also worth noting

`build.cmd Clean` does not clear `test/src/bin`, so switching the local SDK override leaves the previous wave's assemblies behind and every test dies in `OneTimeSetUp` with a `TypeLoadException` on `JetBrains.ReSharper.Feature.Services`. Removing `test/src/bin`, `test/src/obj` and the plugin's `bin`/`obj` by hand is what actually resets it. Worth folding into `Clean`.

**Comment by olsh** [comment]
The first half is on `fix/201-stable-wave-completion-tests` (`63060fd`), not yet opened as a pull request: it makes the test project compile on 2026.2 and keeps 2026.3 at 273/273. The gold work is what remains.
